# make file generated by gryphel build system (which is trash, btw)

mk_COptionsCommon = -c -Wall -Wmissing-prototypes -Wno-uninitialized -Wundef -Wstrict-prototypes -Icfg/ -Isrc/
mk_COptionsOSGLU = $(mk_COptionsCommon) -Os
mk_COptions = $(mk_COptionsCommon) -Os

.PHONY: TheDefaultOutput clean

TheDefaultOutput : minivmac.exe

bld/PROGMAIN.o : src/PROGMAIN.c
	gcc "src/PROGMAIN.c" -o "bld/PROGMAIN.o" $(mk_COptions)
bld/OSGLUWIN.o : src/UI/WIN32/OSGLUWIN.c src/LANG/STRCNENG.h cfg/STRCONST.h src/LANG/INTLCHAR.h src/UI/COMOSGLU.h src/UI/CONTROLM.h cfg/CNFGGLOB.h
	gcc "src/UI/WIN32/OSGLUWIN.c" -o "bld/OSGLUWIN.o" $(mk_COptions)
bld/GLOBGLUE.o : src/GLOBGLUE.c
	gcc "src/GLOBGLUE.c" -o "bld/GLOBGLUE.o" $(mk_COptions)
bld/M68KITAB.o : src/HW/M68K/M68KITAB.c cfg/CNFGGLOB.h
	gcc "src/HW/M68K/M68KITAB.c" -o "bld/M68KITAB.o" $(mk_COptions)
bld/MINEM68K.o : src/HW/M68K/MINEM68K.c
	gcc "src/HW/M68K/MINEM68K.c" -o "bld/MINEM68K.o" $(mk_COptions)
bld/VIAEMDEV.o : src/HW/VIA/VIAEMDEV.c
	gcc "src/HW/VIA/VIAEMDEV.c" -o "bld/VIAEMDEV.o" $(mk_COptions)
bld/IWMEMDEV.o : src/HW/DISK/IWMEMDEV.c
	gcc "src/HW/DISK/IWMEMDEV.c" -o "bld/IWMEMDEV.o" $(mk_COptions)
bld/SCCEMDEV.o : src/HW/SCC/SCCEMDEV.c
	gcc "src/HW/SCC/SCCEMDEV.c" -o "bld/SCCEMDEV.o" $(mk_COptions)
bld/RTCEMDEV.o : src/HW/RTC/RTCEMDEV.c
	gcc "src/HW/RTC/RTCEMDEV.c" -o "bld/RTCEMDEV.o" $(mk_COptions)
bld/ROMEMDEV.o : src/PATCHES/ROMEMDEV.c
	gcc "src/PATCHES/ROMEMDEV.c" -o "bld/ROMEMDEV.o" $(mk_COptions)
bld/SCSIEMDV.o : src/HW/SCSI/SCSIEMDV.c
	gcc "src/HW/SCSI/SCSIEMDV.c" -o "bld/SCSIEMDV.o" $(mk_COptions)
bld/SONYEMDV.o : src/HW/DISK/SONYEMDV.c
	gcc "src/HW/DISK/SONYEMDV.c" -o "bld/SONYEMDV.o" $(mk_COptions)
bld/SCRNEMDV.o : src/HW/SCREEN/SCRNEMDV.c
	gcc "src/HW/SCREEN/SCRNEMDV.c" -o "bld/SCRNEMDV.o" $(mk_COptions)
bld/MOUSEMDV.o : src/HW/MOUSE/MOUSEMDV.c
	gcc "src/HW/MOUSE/MOUSEMDV.c" -o "bld/MOUSEMDV.o" $(mk_COptions)
bld/KBRDEMDV.o : src/HW/KBRD/KBRDEMDV.c
	gcc "src/HW/KBRD/KBRDEMDV.c" -o "bld/KBRDEMDV.o" $(mk_COptions)
bld/SNDEMDEV.o : src/HW/SOUND/SNDEMDEV.c
	gcc "src/HW/SOUND/SNDEMDEV.c" -o "bld/SNDEMDEV.o" $(mk_COptions)
bld/DATE2SEC.o : src/UTIL/DATE2SEC.c
	gcc "src/UTIL/DATE2SEC.c" -o "bld/DATE2SEC.o" $(mk_COptions)

# todo: add files things that aren't the mac plus
bld/ADBEMDEV.o : src/HW/ADB/ADBEMDEV.c
	gcc "src/HW/ADB/ADBEMDEV.c" -o "bld/ADBEMDEV.o" $(mk_COptions)
bld/PMUEMDEV.o : src/HW/POWERMAN/PMUEMDEV.c
	gcc "src/HW/POWERMAN/PMUEMDEV.c" -o "bld/PMUEMDEV.o" $(mk_COptions)

ObjFiles = \
	bld/MINEM68K.o \
	bld/OSGLUWIN.o \
	bld/GLOBGLUE.o \
	bld/M68KITAB.o \
	bld/VIAEMDEV.o \
	bld/IWMEMDEV.o \
	bld/SCCEMDEV.o \
	bld/RTCEMDEV.o \
	bld/ROMEMDEV.o \
	bld/SCSIEMDV.o \
	bld/SONYEMDV.o \
	bld/SCRNEMDV.o \
	bld/MOUSEMDV.o \
	bld/KBRDEMDV.o \
	bld/SNDEMDEV.o \
	bld/PROGMAIN.o \
	bld/DATE2SEC.o
#	bld/ADBEMDEV.o \
#	bld/PMUEMDEV.o \


bld/main.res: src/UI/WIN32/main.rc
	windres.exe -i "src/UI/WIN32/main.rc" --input-format=rc -o "bld/main.res" -O coff  --include-dir SRC


minivmac.exe : $(ObjFiles) bld/
	gcc \
		-o "minivmac.exe" \
		$(ObjFiles) -mwindows -lwinmm -lole32 -luuid

clean :
	rm -f $(ObjFiles)
	rm -f "bld/"
	rm -f "minivmac.exe"
